for /R %%c in (chractor*) do del "%%c"
::pause ...
for /R %%c in (output*) do del "%%c"
::pause ...
for /R %%c in (period*) do del "%%c"
::pause ...
for /R %%c in (progress*) do del "%%c"
::pause ...
for /R %%c in (randop*) do del "%%c"
::pause ...
for /R %%c in (result*) do del "%%c"
::pause ...
for /R %%c in (merge*) do del "%%c"
pause ...